volumes:
  poptape_messages:
    name: poptape_messages

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/messages/api:v0.1
    ports:
      - "1900:8090"
    restart: always
    depends_on:
      - mongodb
    networks:
      - poptape
  mongodb:
    image: mongo
    restart: always
    ports:
      - "1901:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - poptape_messages:/data/db
    networks:
      - poptape
networks:
  poptape:
    external: true
  
